name: deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'
          bundler-cache: true

      - name: Install Mermaid
        run: npm install -g @mermaid-js/mermaid-cli

      - name: Setup deploy options
        id: setup
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          echo "SRC_BRANCH=main" >> $GITHUB_OUTPUT
          echo "DEPLOY_BRANCH=gh-pages" >> $GITHUB_OUTPUT

      - name: Deploy website
        run: |
          yes | bash bin/deploy --verbose \
            --src ${{ steps.setup.outputs.SRC_BRANCH }} \
            --deploy ${{ steps.setup.outputs.DEPLOY_BRANCH }}